version: '3'

services: 
  asgncsvserver:
    image: infracloudio/csvserver:latest
    container_name: csvserver_container
    environment:
    - CSVSERVER_BORDER=Orange
    ports:
    - 9393:9300
    volumes:
    - ./inputFile:/csvserver/inputdata
  
  promthe:  
    image: prom/prometheus:v2.22.0
    container_name: monitoring
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
    - 9090:9090
