version: '3'

services: 
  asgncsvserver:
    image: infracloudio/csvserver:latest
    container_name: csvserver_container
    environment:
    - CSVSERVER_BORDER=Orange
    ports:
    - 9393:9300
    volumes:
    - ./inputFile:/csvserver/inputdata
